### ISSUE TITLE
suit regexp is weak

### ISSUE THREAD

**Issue by giuseppeg** [maximkoretskiy/postcss-autoreset#16]
Hi, I know that regexps are expensive but the one for suit is very flaky and weak.

For instance the plugin resets things like 

```css
.Component[aria-hidden="true"] {}
```

which results in specificity issues e.g.:

```css
.Component { 
  font-size: 3em;
}

.Component[aria-hidden="true"] {
  display: none;
}
```

Is compiled to

```css
.Component,
.Component[aria-hidden="true"] {
   font-size: medium;
}

.Component { 
  font-size: 3em;
}

.Component[aria-hidden="true"] {
  display: none;
}
```

and because `.Component[aria-hidden="true"]` is more specific than `.Component` `font-size: 3em` is overridden.

You may want to use `postcss-bem-linter`'s [regexps](https://github.com/postcss/postcss-bem-linter/blob/master/lib/preset-patterns.js).

[We are considering](https://github.com/suitcss/preprocessor/issues/43) to add this plugin to suitcss and this is a blocker.
Let me know if you need some help ✌️
