### ISSUE TITLE
Put all resets to one rule

### ISSUE THREAD

**Issue by ai** [maximkoretskiy/postcss-autoreset#4]
Right now we insert reset properties directly to rule. As result after `postcss-intial` we have long list of properties in rule. Of course, it is not a problem for CSS size because of gzip, but it is a problem for DevTool inspecting.

My suggestion. Input:

```css
.a {
  color: black;
}
.b {
  color: white;
}
```

Output:

```css
.a, .b {
  all: initial;
}
.a {
  color: black;
}
.b {
  color: white;
}
```
